config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "categories#index"
    resources :categories do
      resources :words, except: [:show]
    end
    resources :users
    resources :categories, except: [:show]
  end

  root   "static_pages#home"
  get    "signup"  => "users#new"
  get    "login"   => "sessions#new"
  post   "login"   => "sessions#create"
  delete "logout"  => "sessions#destroy"
  get "password_resets/new"
  get "password_resets/edit"
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :activities, only: [:create, :destroy]
  resources :relationships, only: [:index, :create, :destroy]
  resources :words, only: [:index, :create, :destroy]
  resources :categories do
    resources :lessons, only: [:index]
  end
  resources :lessons, only: [:show, :update] do
    resources :results, only: [:index]
  end
  resources :results, only: [:show, :update]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @feed_items = Activity.feed(current_user.id).paginate page: params[:page],
      per_page: Settings.perpage if logged_in?
  end
end

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render "shared/user_info" %>
      </section>
      <section>
        <div>
          <h1><%= link_to t("activity.word"), words_path %></h1>
        </div>
        <div>
          <h1><%= link_to t("activity.lesson"), categories_path %></h1>
        </div>
      </section>
    </aside>
    <div class="col-md-8">
      <h3><%= t "activity.activities_show" %></h3>
      <%= render "shared/feed" %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1><%= t "welcom" %></h1>
    <h2>
      <%= t "welcom1" %>
      <a href="http://www.railstutorial.org/"><%= t "ruby_on_rails" %></a><%= t "welcom2" %>
    </h2>
    <%= link_to t("staticpage.signup"), signup_path, class: "btn btn-lg btn-primary" %>
  </div>
  <%= link_to image_tag("rails.png", alt: t("rails_logo")),
    "http://rubyonrails.org/images/rails.png" %>
<% end %>