config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "categories#index"
    resources :categories do
      resources :words, except: [:show]
    end
    resources :users
    resources :categories, except: [:show]
  end

  root   "static_pages#home"
  get    "signup"  => "users#new"
  get    "login"   => "sessions#new"
  post   "login"   => "sessions#create"
  delete "logout"  => "sessions#destroy"
  get "password_resets/new"
  get "password_resets/edit"
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :activities, only: [:create, :destroy]
  resources :relationships, only: [:index, :create, :destroy]
  resources :words, only: [:index, :create, :destroy]
  resources :categories do
    resources :lessons, only: [:index]
  end
  resources :lessons, only: [:show, :update] do
    resources :results, only: [:index]
  end
  resources :results, only: [:show, :update]
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category
  belongs_to :lesson
  has_many :answers, dependent: :destroy
  has_many :results
  accepts_nested_attributes_for :answers, allow_destroy: true

  LEARNED_WORDS = "id in (SELECT word_id from results where lesson_id in (
    select id from lessons where user_id = :user_id))"

  scope :all_word_category, ->(category_id){where category_id: category_id}
  scope :learned, ->(user_id){where LEARNED_WORDS, user_id: user_id}
  scope :not_learned, ->(user_id){where.not LEARNED_WORDS, user_id: user_id}

  class << self
    def all_status
      Settings.word.status
    end

    def generate_words_in_lessons category_id
      Word.all_word_category(category_id).shuffle[0..Settings.lesson.lessonsize]
    end

    def word_by_filter user_id, category_id, status
      case status
      when Settings.word.all_word
        Word.all_word_category category_id
      when Settings.word.learned_word
        Word.all_word_category(category_id).learned user_id
      else
        Word.all_word_category(category_id).not_learned user_id
      end
    end

    def save_words_to_results lesson_id, words
      words.each do |word|
        result = Result.new lesson_id: lesson_id, word_id: word.id
        result.save!
      end
    end
  end

  def correct_answer
    answers.find_by correct_answer: true
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :authenticate_admin
  before_action :load_category
  before_action :load_word, only: [:edit, :update, :destroy]

  def index
    @answers_number = Settings.answers_number
    @words = @category.words.paginate page: params[:page], per_page: Settings.perpage
  end

  def new
    @word = Word.new
    Settings.answers_number_size.times {@word.answers.build}
  end

  def edit
  end

  def update
    if @word.update_attributes word_params
      flash[:success] = t "admin.word.update_success"
      redirect_to [:admin, :category, :words]
    else
      flash[:danger] = t "admin.word.update_failed"
      render :edit
    end
  end

  def destroy
    @word.destroy
    flash[:success] = t "admin.word.deleted_word"
    redirect_to [:admin, :category, :words]
  end

  def create
    @word = @category.words.build word_params
    if @word.save
      flash[:success] = t "admin.word.create_word_success"
      redirect_to [:admin, :category, :words]
    else
      render :new
    end
  end

  private
  def word_params
    params.require(:word).permit :name, answers_attributes: [:id, :name, :correct_answer, :_destroy]
  end

  def load_category
    @category = Category.find params[:category_id]
  end

  def load_word
    @word = Word.find params[:id]
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :load_word

  def index
    @word_filter = params[:button].nil? ? Word.all : Word.word_by_filter.(@current_user.id, @category, @status)
    @words = @word_filter.paginate page: params[:page], per_page: Settings.perpage
  end

  private
  def load_word
    @categories = Category.all
    @category = params[:category].to_i
    @word_statuses = Word.all_status
    @status = params[:status].nil? ? @word_statuses[0] : params[:status].to_i
  end
end

app/views/admin/words/_answer_fields.html.erb
<div class="nested-fields">
  <div>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div>
    <%= f.check_box :correct_answer %>
  </div>
  <div>
    <%= link_to_remove_fields t("admin.word.remove"), f %>
  </div>
</div>

app/views/admin/words/_word.html.erb
<tr>
  <td><%= word.name %>
    <%= link_to t("admin.word.edit"), edit_admin_category_word_path(@category, word) %>
    <%= link_to t("admin.word.delete"), admin_category_word_path(@category, word),
      method: :delete, data: {confirm: t("admin.word.you_sure")}  %>
  </td>
  <% word.answers.each do |answer| %>
    <td>
      <%= answer.name %>
      <i class="glyphicon glyphicon-<%= answer.correct_answer? ? "ok" : "remove" %>" ></i>
    </td>
  <% end %>
</tr>

app/views/admin/words/edit.html.erb
<% provide :title, t("admin.word.edit") %>
<h1><%= t "admin.word.edit_word" %></h1>
<%= form_for [:admin, @category, @word] do |f| %>
  <%= render "shared/error_messages", object: @word %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
    <%= link_to_add_fields t("answer.add"), f, :answers %>
  </div>
  <%= f.hidden_field :category_id, value: :category_id %>
  <%= f.label :answers %>
  <div>
    <%= f.fields_for :answers do |answer| %>
      <%= render "answer_fields", f: answer %>
    <% end %>
  </div>
  <%= f.submit t("admin.word.submit") %>
<% end %>

app/views/admin/words/index.html.erb
<% provide :title, t("admin.word.words") %>
<div class="row">
  <h1><%= @category.name %></h1>
  <table class="table table-striped">
    <%= link_to t("admin.word.create_new_word"), new_admin_category_word_path %>
    <tr>
      <th><%= t "admin.word.words" %></th>
      <% @answers_number.each do |answer| %>
        <th><%= answer %></th>
      <% end %>
    </tr>
    <%= render @words %>
  </table>
  <%= will_paginate %>
</div>

app/views/admin/words/new.html.erb
<% provide :title, t("admin.word.create_word") %>
<h1><%= t "admin.word.create_word" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @category, @word] do |f| %>
      <%= render "shared/error_messages", object: @word %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      <%= link_to_add_fields t("admin.word.add"), f, :answers  %>

      <%= f.hidden_field :category_id, value: :category_id %>
      <%= f.label :answers %>

      <%= f.fields_for :answers do |answer| %>
        <div>
          <%= render "answer_fields", f: answer %>
        </div>
      <% end %>
      <%= f.submit t("admin.category.save"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>