config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "categories#index"
    resources :categories do
      resources :words, except: [:show]
    end
    resources :users
    resources :categories, except: [:show]
  end

  root   "static_pages#home"
  get    "signup"  => "users#new"
  get    "login"   => "sessions#new"
  post   "login"   => "sessions#create"
  delete "logout"  => "sessions#destroy"
  get "password_resets/new"
  get "password_resets/edit"
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :activities, only: [:create, :destroy]
  resources :relationships, only: [:index, :create, :destroy]
  resources :words, only: [:index, :create, :destroy]
  resources :categories do
    resources :lessons, only: [:index]
  end
  resources :lessons, only: [:show, :update] do
    resources :results, only: [:index]
  end
  resources :results, only: [:show, :update]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :lessons, dependent: :destroy
  has_many :words, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_admin
  before_action :load_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.paginate page: params[:page]
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "admin.category.update_success"
      redirect_to admin_root_url
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:success] = t "admin.category.destroy_success"
    redirect_to admin_root_url
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "admin.category.created_category"
      redirect_to admin_root_url
    else
      render :new
    end
  end

  def new
    @category = Category.new
  end

  private
  def category_params
    params.require(:category).permit :name, :description
  end

  def load_category
    @category = Category.find params[:id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user, only: [:index]

  def index
    @categories = Category.paginate page: params[:page]
  end
end

app/views/categories/index.html.erb
<div class="container">
<section>
  <div class="row">
    <h1><%= t "category.all" %></h1>
    <table class="table table-striped">
      <tr>
        <th>#</th>
        <th><%= t "category.name" %></th>
        <th><%= t "category.description" %></th>
        <th><%= t "category.start" %></th>
      </tr>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.id %></td>
          <td><b><%= category.name %></b></td>
          <td><%= category.description %></td>
          <td><%= link_to t("category.start"), category_lessons_path(category) %></td>
        </tr>
      <% end %>
    </table>
  </div>
</section>